dist: trusty
sudo: required
language:
        - cpp
compiler:
        - gcc
addons:
         coverity_scan:
                 project:
                        name: rpulid2/libuv
                        version: master
                        description: Libuv fork for coverity scan
                 notification_email: rodrigo.pulido@intel.com
                 build_command_prepend: mkdir -p build && cd build && cmake ../
                 build_command: make
                 branch_pattern: coverity_scan
          apt:
                  sources:
                         - ubuntu-toolchain-r-test
                  packages:
                          - gcc-6
                          - g++-6
                          - cmake
                           


