env:
        global:
                # COVERITY_SCAN_TOKEN
                # ** specific to your project **
                - secure: "xxxx"
addons:
        coverity_scan:
                project:
                        name: rpulid2/libuv
                        version: master
                        description: Libuv fork for coverity scan

                notification_email: rodrigo.pulido@intel.com
                build_command_prepend: ./autogen.sh
                build_command_prepend: ./configure
                build_command: make
                branch_pattern: coverity_scan
