- os: linux
  env: 
  addons:
          apt:
                  sources:
                          - ubuntu-toolchain-r-test
                  packages:
                          - gcc-6
                          - g++-6
                  coverity_scan:
                          project:
                                  name: "rpulid2/libuv_fork"
                                  description: "Coverity Scan"
                                  notification_email: rodrigo.pulido@intel.com
                                  build_command_prepend: "cmake -DCMAKE_CXX_COMPILER=g++-6 .."
                                  build_command: "make"
                                  branch_pattern: master

